### ISSUE TITLE
WellKnownSchemaFilterPass does not support Symfony\Component\ExpressionLanguage\Expression

### ISSUE THREAD

**Issue by oleg-andreyev** [doctrine/DoctrineBundle#1136]
Having the following configuration:

DI Definition 
<details>

```
        <service id="session.handler.pdo" class="Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler">
            <argument>mysql:host=%sessions_db_host%;port=%sessions_db_port%;dbname=%sessions_db_name%</argument>
            <argument type="expression">service('session.database_options_factory').getOptions()</argument>
            <argument>%session.storage.options%</argument>
        </service>
```

</details>

Exception
<details>

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot use object of type Symfony\Component\ExpressionLanguage\Expression as array in /project/vendor/doctrine/doctrine-bundle/DependencyInjection/Compiler/WellKnownSchemaFilterPass.php:43
Stack trace:
#0 /opcart/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(140): Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\WellKnownSchemaFilterPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(643): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\K in /project/vendor/doctrine/doctrine-bundle/DependencyInjection/Compiler/WellKnownSchemaFilterPass.php on line 43
```

</details>

Dump
<details>

```
string(74) "Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler"
array(3) {
  [0]=>
  string(79) "mysql:host=%sessions_db_host%;port=%sessions_db_port%;dbname=%sessions_db_name%"
  [1]=>
  object(Symfony\Component\ExpressionLanguage\Expression)#3100 (1) {
    ["expression":protected]=>
    string(56) "service('session.database_options_factory').getOptions()"
  }
  [2]=>
  string(25) "%session.storage.options%"
}
```

</details>

It's because Pass is assuming that Arguments are always an array
https://github.com/doctrine/DoctrineBundle/blob/fbc977b73586ee75b1575ce952b9f3bb482dee2f/DependencyInjection/Compiler/WellKnownSchemaFilterPass.php#L35

**Comment by dmaicher** [comment]
Indeed we cannot support such cases where the config is dynamically injected based on an expression at run-time.

@oleg-andreyev are you up for working on a fix? We need to check if the argument is an array then and ignore such expression language cases. Would be good to cover the other services then as well like

https://github.com/doctrine/DoctrineBundle/blob/fbc977b73586ee75b1575ce952b9f3bb482dee2f/DependencyInjection/Compiler/WellKnownSchemaFilterPass.php#L31

**Comment by oleg-andreyev** [comment]
@dmaicher yes, I’m getting familiar with code around and trying to find a right solution .

**Comment by ostrolucky** [comment]
This class is getting deprecated and shouldn't be relied on, see https://github.com/doctrine/DoctrineBundle/issues/1176
